const menuPizza = [ 
  {
    "id": 0,
    "nombre":"Margharite",
    "descrip": "Ingredienti: Bocconcino Fior di latte, pomodore, albahaca, olio d'oliva, albahaca.",
    "precio": 1250,
    "cantidad": 1,
    "imagen": '../Multimedia/PIZZAS/margarita.jpg',
  },
  {
    "id": 1,
    "nombre":"Quattro Formaggi",
    "descrip": "Ingredienti: Bocconcino Fior di latte, Roquefort, Provolone, Reggianite olio d'oliva, salsa bianca.",
    "precio": 1300,
    "cantidad": 1,
    "imagen": '../Multimedia/PIZZAS/17431-pizza-suprema-ai-formaggi-K-20220125.jpg',
  },
  {
    "id": 2,
    "nombre":"Provolone",
    "descrip": "Ingredienti: Bocconcino Fior di latte, Provolone, olive, olio d'oliva, pesto alla genovese.",
    "precio": 1450,
    "cantidad": 1,
    "imagen": '../Multimedia/PIZZAS/provo.jpg',
  },
  {
    "id": 3,
    "nombre":"Funghi",
    "descrip": "Ingredienti: Bocconcino Fior di latte, Funghi Portobello, olio d'oliva.",
    "precio": 1500,
    "cantidad": 1,
    "imagen": '../Multimedia/PIZZAS/istockphoto-1350259421-612x612.jpg',
  },
  {
    "id": 4,
    "nombre":"Della casa",
    "descrip": "Ingredienti: Bocconcino Fior di latte, Reggianite, Funghi Portobello, Cipolla caramellata, Albahaca, olio d'oliva.",
    "precio": 1600,
    "cantidad": 1,
    "imagen": '../Multimedia/PIZZAS/istockphoto-474338200-612x612.jpg',
  },
  {
    "id": 5,
    "nombre":"Veggie",
    "descrip": "Ingredienti: Farina di riso, Queso Paparella, Pomodore, albahaca, rúcula, hongos, olio d'oliva.",
    "precio": 1250,
    "cantidad": 1,
    "imagen": '../Multimedia/PIZZAS/pizza-napoletana-vegana-3.jpg',
  },
]

const menuWine = [
  {
    "id": 0,
    "nombre":"Luigi Bosca Malbec",
    "descrip": "Wine",
    "precio": 1700,
    "cantidad": 1,
    "imagen": '../Multimedia/Vinos/200928-Luigi_Bosca-T1-Malbec-CAM1-b.png',
  },
  {
    "id": 1,
    "nombre":"Luigi Bosca La Linda",
    "descrip": "Wine",
    "precio": 1450,
    "cantidad": 1,
    "imagen": '../Multimedia/Vinos/cabernetluigi.jpg',
  },
  {
    "id": 2,
    "nombre":"Luigi Bosca Cabernet Sauvignion",
    "descrip": "Wine",
    "precio": 1300,
    "cantidad": 1,
    "imagen": '../Multimedia/vinos/linda.jpg',
  },
  {
    "id": 3,
    "nombre":"MM Blend",
    "descrip": "Wine",
    "precio": 1250,
    "cantidad": 1,
    "imagen": '../Multimedia/vinos/mm.webp',
  },
  {
    "id": 4,
    "nombre":"MM Malbec Street dog",
    "descrip": "Wine",
    "precio": 1250,
    "cantidad": 1,
    "imagen": '../Multimedia/Vinos/perrocallejero.jpg',
  },
  {
    "id": 5,
    "nombre":"MM Pispi Blend",
    "descrip": "Wine",
    "precio": 1250,
    "cantidad": 1,
    "imagen": '../Multimedia/VINOS/pispi.jpg',
  },
  {
    "id": 6,
    "nombre":"Matias Ricitelli Malbec Apple ",
    "descrip": "Wine",
    "precio": 1250,
    "cantidad": 1,
    "imagen": '../Multimedia/VINOS/APPLE.webp',
  },
  {
    "id": 7,
    "nombre":"Matias Ricitelli Malbec Apple ",
    "descrip": "Wine",
    "precio": 1250,
    "cantidad": 1,
    "imagen": '../Multimedia/VINOS/vinyard.png',
  },
]

const menuNaturalJuice = [
  {
    "id": 0,
    "nombre":"Natural Juice Strawerry",
    "descrip": "Juice Natural",
    "precio": 1250,
    "cantidad": 1,
    "imagen": '../Multimedia/JUICE/trawberry-berry-juice.jpg',
  },
  {
    "id": 1,
    "nombre":"Natural Juice Orange",
    "descrip": "Juice Natural",
    "precio": 1250,
    "cantidad": 1,
    "imagen": '../Multimedia/JUICE/juice-orange.jpg',
  },
  {
    "id": 2,
    "nombre":"Natural Juice Lemonade Grapefruit",
    "descrip": "Juice Natural",
    "precio": 1250,
    "cantidad": 1,
    "imagen": '../Multimedia/JUICE/lemonade.jpg',
  },
  {
    "id": 3,
    "nombre":"Natural Juice Grapefruit",
    "descrip": "Juice Natural",
    "precio": 1250,
    "cantidad": 1,
    "imagen": '../Multimedia/JUICE/grapefruit-juice.jpg',
  },
  {
    "id": 4,
    "nombre":"Natural Juice Peach",
    "descrip": "Juice Natural",
    "precio": 1250,
    "cantidad": 1,
    "imagen": '../Multimedia/JUICE/peach-juice.jpg',
  },
  {
    "id": 5,
    "nombre":"Natural Juice Mix Choice",
    "descrip": "Juice Natural",
    "precio": 1250,
    "cantidad": 1,
    "imagen": '../Multimedia/JUICE/cuales_son_las_frutas_de_invierno_7504_orig.jpg',
  },
]

const menuCoffee = [
  {
  "id": 0,
  "nombre":"Coffee Espresso ",
  "descrip": "Coffee",
  "precio": 1250,
  "cantidad": 1,
  "imagen": '../Multimedia/COFFE/cafe-espresso.jpg',
},
{
  "id": 1,
  "nombre":"Coffee Machiatto",
  "descrip": "Coffee",
  "precio": 1250,
  "cantidad": 1,
  "imagen": '../Multimedia/COFFE/Espresso_macchiato_Chiang_Mai.jpg',
},
{
  "id": 2,
  "nombre":"Coffee Ristretto",
  "descrip": "Coffee",
  "precio": 1250,
  "cantidad": 1,
  "imagen": '../Multimedia/COFFE/ristretto-1.jpg',
},
{
  "id": 3,
  "nombre":"Coffee Cappucino",
  "descrip": "Coffee",
  "precio": 1250,
  "cantidad": 1,
  "imagen": '../Multimedia/COFFE/cafe-capuchino.jpg',
},
{
  "id": 4,
  "nombre":"Coffee With Milk",
  "descrip": "Coffee",
  "precio": 1250,
  "cantidad": 1,
  "imagen": '../Multimedia/COFFE/cafe-con-leche.jpg',
},
{
  "id": 5,
  "nombre":"Coffee Moka",
  "descrip": "Coffee",
  "precio": 1250,
  "cantidad": 1,
  "imagen": '../Multimedia/COFFE/cafe-moka.jpg',
},
{
  "id": 6,
  "nombre":"Coffee Bombon",
  "descrip": "Coffee",
  "precio": 1250,
  "cantidad": 1,
  "imagen": '../Multimedia/COFFE/cafe-bombon.jpg',
},
{
  "id": 7,
  "nombre":"Lungo ",
  "descrip": "Coffee",
  "precio": 1250,
  "cantidad": 1,
  "imagen": '../Multimedia/COFFE/Café-largo.jpg',
},
]


  